package view;

import ahecproject.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JPanel;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.*;

/**
 *
 * @author Michał Pochopień @ the hungry beavers
 */
public class JFrameMain extends javax.swing.JFrame {

    JFreeChart ratioChart;
    XYSeries ratioSeries;
    int counter = 0;
    double lastRatio = 0.0, minimum = 0.0, max = 22.0;
    Thread runnable;

    /**
     * Creates new formonitor JFramonitoreMain
     */
    public JFrameMain() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    System.out.println("NIMBUS!!!!");
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();
        this.showGraph();
        runnable = new Thread() {

            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(100);
                        JFrameMain.this.refreshGraph();
                        JFrameMain.this.refreshIndicators();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };

        runnable.start();
    }

    /**
     * This monitorethod is called fromonitor within the constructor to initialize the formonitor.
     * WARNING: Do NOT monitorodify this code. The content of this monitorethod is always
    regenerated by the Formonitor Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonComputationsPanel = new javax.swing.JButton();
        jButtonSettingsPanel = new javax.swing.JButton();
        jButtonAddUserPanel = new javax.swing.JButton();
        jLayeredPaneMain = new javax.swing.JLayeredPane();
        jPanelAddUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneLogin = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jPasswordFieldPasswordRepeat = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPanelSettings = new javax.swing.JPanel();
        jButtonAutomatic = new javax.swing.JButton();
        jButtonManual = new javax.swing.JButton();
        jButtonReactivate = new javax.swing.JButton();
        jPanelComputations = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLiftStop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonDragStop = new javax.swing.JButton();
        jButtonOptimiserStop = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelLiftIndicator = new javax.swing.JLabel();
        jLabelDragIndicator = new javax.swing.JLabel();
        jLabelOptimiserIndicator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(-12829897,true));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N

        jButtonComputationsPanel.setText("Computations");
        jButtonComputationsPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputationsPanelActionPerformed(evt);
            }
        });

        jButtonSettingsPanel.setText("Settings");
        jButtonSettingsPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsPanelActionPerformed(evt);
            }
        });

        jButtonAddUserPanel.setText("Add User");
        jButtonAddUserPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonComputationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComputationsPanel)
                    .addComponent(jButtonSettingsPanel)
                    .addComponent(jButtonAddUserPanel)))
        );

        jScrollPane1.setViewportView(jTextPaneLogin);

        jLabel5.setText("login");

        jLabel6.setText("password");

        jButton1.setText("Add user");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("repeat");

        javax.swing.GroupLayout jPanelAddUserLayout = new javax.swing.GroupLayout(jPanelAddUser);
        jPanelAddUser.setLayout(jPanelAddUserLayout);
        jPanelAddUserLayout.setHorizontalGroup(
            jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddUserLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldPasswordRepeat, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanelAddUserLayout.setVerticalGroup(
            jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddUserLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldPasswordRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jPanelAddUser.setBounds(0, 0, 720, 340);
        jLayeredPaneMain.add(jPanelAddUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonAutomatic.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonAutomatic.setText("Automatic");
        jButtonAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutomaticActionPerformed(evt);
            }
        });

        jButtonManual.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonManual.setText("Manual");
        jButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualActionPerformed(evt);
            }
        });

        jButtonReactivate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonReactivate.setText("Reactivate");
        jButtonReactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReactivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonManual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAutomatic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jButtonReactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jButtonAutomatic, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonManual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonReactivate, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelSettings.setBounds(0, 0, 560, 130);
        jLayeredPaneMain.add(jPanelSettings, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14));
        jLabel1.setText("Lift solver");

        jButtonLiftStop.setFont(new java.awt.Font("SansSerif", 1, 14));
        jButtonLiftStop.setForeground(new java.awt.Color(-65536,true));
        jButtonLiftStop.setText("STOP");
        jButtonLiftStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiftStopActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14));
        jLabel2.setText("Drag solver");

        jButtonDragStop.setFont(new java.awt.Font("SansSerif", 1, 14));
        jButtonDragStop.setForeground(new java.awt.Color(-65536,true));
        jButtonDragStop.setText("STOP");
        jButtonDragStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDragStopActionPerformed(evt);
            }
        });

        jButtonOptimiserStop.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonOptimiserStop.setForeground(new java.awt.Color(-65536,true));
        jButtonOptimiserStop.setText("STOP");
        jButtonOptimiserStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOptimiserStopActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Optimiser");

        jLabelLiftIndicator.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabelLiftIndicator.setText(" ");

        jLabelDragIndicator.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabelDragIndicator.setText(" ");

        jLabelOptimiserIndicator.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelOptimiserIndicator.setText(" ");

        javax.swing.GroupLayout jPanelComputationsLayout = new javax.swing.GroupLayout(jPanelComputations);
        jPanelComputations.setLayout(jPanelComputationsLayout);
        jPanelComputationsLayout.setHorizontalGroup(
            jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelComputationsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComputationsLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addGap(76, 76, 76))
                        .addComponent(jButtonLiftStop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComputationsLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addGap(62, 62, 62))
                        .addComponent(jButtonDragStop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelComputationsLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(74, 74, 74))
                        .addComponent(jButtonOptimiserStop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
            .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelComputationsLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jLabelLiftIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(108, 108, 108)
                    .addComponent(jLabelDragIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(108, 108, 108)
                    .addComponent(jLabelOptimiserIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );
        jPanelComputationsLayout.setVerticalGroup(
            jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelComputationsLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLiftStop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDragStop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOptimiserStop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(154, Short.MAX_VALUE)))
            .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelComputationsLayout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addGroup(jPanelComputationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDragIndicator)
                        .addComponent(jLabelLiftIndicator)
                        .addComponent(jLabelOptimiserIndicator))
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        jPanelComputations.setBounds(0, 0, 570, 310);
        jLayeredPaneMain.add(jPanelComputations, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLayeredPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonLiftStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiftStopActionPerformed
    AHECProject.liftSolver.interrupt();
}//GEN-LAST:event_jButtonLiftStopActionPerformed

private void jButtonDragStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDragStopActionPerformed
    AHECProject.dragSolver.interrupt();
}//GEN-LAST:event_jButtonDragStopActionPerformed

private void jButtonOptimiserStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptimiserStopActionPerformed
    AHECProject.optimiser.interrupt();
}//GEN-LAST:event_jButtonOptimiserStopActionPerformed

private void jButtonAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutomaticActionPerformed
    AHECProject.monitor.setAutomaticMode();
}//GEN-LAST:event_jButtonAutomaticActionPerformed

private void jButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
    AHECProject.monitor.setManualMode();
}//GEN-LAST:event_jButtonManualActionPerformed

private void jButtonReactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReactivateActionPerformed
    AHECProject.monitor.reactivate();
}//GEN-LAST:event_jButtonReactivateActionPerformed

private void jButtonComputationsPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputationsPanelActionPerformed
    jPanelComputations.setVisible(true);
    jPanelAddUser.setVisible(false);
    jPanelSettings.setVisible(false);
}//GEN-LAST:event_jButtonComputationsPanelActionPerformed

private void jButtonSettingsPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsPanelActionPerformed
    jPanelComputations.setVisible(false);
    jPanelAddUser.setVisible(false);
    jPanelSettings.setVisible(true);
}//GEN-LAST:event_jButtonSettingsPanelActionPerformed

private void jButtonAddUserPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserPanelActionPerformed
    jPanelComputations.setVisible(false);
    jPanelAddUser.setVisible(true);
    jPanelSettings.setVisible(false);
}//GEN-LAST:event_jButtonAddUserPanelActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    AHECProject.dbManager.insertUser(jTextPaneLogin.getText(), jPasswordFieldPassword.getText());
}//GEN-LAST:event_jButton1ActionPerformed

    private void refreshIndicators() {
        if (AHECProject.monitor.isAutoMode()) {
            jButtonAutomatic.setBackground(Color.orange);
            jButtonManual.setBackground(Color.lightGray);
        } else {
            jButtonAutomatic.setBackground(Color.lightGray);
            jButtonManual.setBackground(Color.orange);
        }

        if (AHECProject.liftSolver.isAlive()) {
            setON(jLabelLiftIndicator);
        } else {
            setOFF(jLabelLiftIndicator);
        }

        if (AHECProject.dragSolver.isAlive()) {
            setON(jLabelDragIndicator);
        } else {
            setOFF(jLabelDragIndicator);
        }

        if (AHECProject.optimiser.isAlive()) {
            setON(jLabelOptimiserIndicator);
        } else {
            setOFF(jLabelOptimiserIndicator);
        }
       
        jPanelComputations.repaint();
    }

    private void setOFF(javax.swing.JLabel label) {
        label.setText("OFF");
        label.setForeground(Color.red);
    }

    private void setON(javax.swing.JLabel label) {
        label.setText("ON");
        label.setForeground(Color.green);
    }

    private void showGraph() {
        ratioSeries = new XYSeries("Lift/Drag");
        ratioSeries.add(0.0, 0.0);
        XYDataset xyDataset = new XYSeriesCollection(ratioSeries);

        ratioChart = ChartFactory.createXYLineChart("Lift/Drag ratio", "Cycle", "Ratio",
                xyDataset, PlotOrientation.VERTICAL, true, true, false);

        ChartFrame frame1 = new ChartFrame("Ratio", ratioChart);
        frame1.setVisible(true);
        frame1.setSize(400, 400);
    }

    /**
     * @param args the comonitormonitorand line argumonitorents
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        System.out.println("TRY!!!!");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    System.out.println("NIMBUS!!!!");
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddUserPanel;
    private javax.swing.JButton jButtonAutomatic;
    private javax.swing.JButton jButtonComputationsPanel;
    private javax.swing.JButton jButtonDragStop;
    private javax.swing.JButton jButtonLiftStop;
    private javax.swing.JButton jButtonManual;
    private javax.swing.JButton jButtonOptimiserStop;
    private javax.swing.JButton jButtonReactivate;
    private javax.swing.JButton jButtonSettingsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDragIndicator;
    private javax.swing.JLabel jLabelLiftIndicator;
    private javax.swing.JLabel jLabelOptimiserIndicator;
    private javax.swing.JLayeredPane jLayeredPaneMain;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAddUser;
    private javax.swing.JPanel jPanelComputations;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JPasswordField jPasswordFieldPasswordRepeat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneLogin;
    // End of variables declaration//GEN-END:variables

    private void refreshGraph() {
        //refresh graph
        if (ratioSeries != null) {
            double ratio = AHECProject.optimiser.getLift() / AHECProject.optimiser.getDrag();
            if (ratio != lastRatio && AHECProject.optimiser.getDrag() != 0.0) {
                counter++;
                if (ratio < minimum) {
                    ratioSeries.add(counter, ratio * 0.3 + minimum);
                } else {
                    ratioSeries.add(counter, ratio);
                }
                lastRatio = ratio;
                //20s -> counter=60
                if (minimum < max) {
                    double x = counter;
                    minimum = 547.0 / 6930000 * (x + 45) * (x + 45) * (x + 45) - 35279.0 / 1386000 * (x + 45) * (x + 45) + 129629.0 / 46200 * x + 11677.0 / 280;
                    System.out.println("counter=" + counter + ", min=" + minimum);
                }
            }
        }
    }
}
